#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal
#
# from: https://github.com/dylanaraps/pywal/issues/322

 # Source generated colors.
. "${HOME}/.cache/wal/colors.sh"

 reload_dunst() {
    pkill dunst
    dunst \
	-frame_width 0 \
	-frame_color "${color2}" \
        -lb "${color7}" \
        -nb "${color7}" \
        -cb "${color7}" \
        -lf "${color2}" \
        -cf "${color2}" \
        -nf "${color2}" &
}

reload_dunst
